// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async takeScreenshot(target: ScreenCaptureTarget | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("take_screenshot", { target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listCaptureDisplays() : Promise<CaptureDisplay[]> {
    return await TAURI_INVOKE("list_capture_displays");
},
async listCaptureWindows() : Promise<CaptureWindow[]> {
    return await TAURI_INVOKE("list_capture_windows");
},
async listDisplaysWithThumbnails() : Promise<CaptureDisplayWithThumbnail[]> {
    return await TAURI_INVOKE("list_displays_with_thumbnails");
},
async listWindowsWithThumbnails() : Promise<CaptureWindowWithThumbnail[]> {
    return await TAURI_INVOKE("list_windows_with_thumbnails");
},
async startRecording(captureTarget: ScreenCaptureTarget) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_recording", { captureTarget }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopRecording() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pauseRecording() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resumeRecording() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discardRecording() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discard_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restartRecording() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restart_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Recording-scoped mic mute. The feed keeps running at its normal cadence and
 * silence is written instead, so muting can't desync audio against video.
 * Returns the resulting state so the caller never has to guess.
 */
async setRecordingMicMuted(muted: boolean) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_recording_mic_muted", { muted }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * One binding for pause and resume — a global shortcut has no way to show two
 * different keys for two halves of the same toggle, and the user pressing
 * "pause" again plainly means resume.
 */
async togglePauseRecording() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_pause_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Binds `hotkey` to `action`, or clears the binding when `hotkey` is `None`.
 * Registration happens immediately so the shortcut is live without a restart,
 * and the store is written so it survives one.
 */
async setHotkey(action: HotkeyAction, hotkey: Hotkey | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_hotkey", { action, hotkey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHotkeys() : Promise<Result<HotkeysStore, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_hotkeys") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createEditorInstance() : Promise<Result<SerializedEditorInstance, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_editor_instance") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startPlayback(fps: number, resolutionBase: XY<number>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_playback", { fps, resolutionBase }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopPlayback() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_playback") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPlayheadPosition(frameNumber: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_playhead_position", { frameNumber }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Renders every frame of the project in order into a socket the frontend
 * composites from.
 * 
 * This is the counterpart to `RenderFrameEvent`, which is a *scrub* API built
 * on a watch channel: last value wins, so asking for frames back-to-back
 * coalesces and a frontend compositor ends up serialised — request, wait,
 * composite, request. Here the renderer runs ahead into a small bounded queue
 * so compositing frame N overlaps rendering N+1, and backpressure runs the
 * whole way back from the socket, so a slow consumer paces the renderer
 * instead of building a backlog.
 * 
 * There is no stop command: closing the socket fails the renderer's `send`,
 * which ends the render.
 */
async startFrameStream(fps: number, resolutionBase: XY<number>, nv12: boolean, maxFrames: number | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_frame_stream", { fps, resolutionBase, nv12, maxFrames }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setProjectConfig(config: ProjectConfiguration) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_project_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateProjectConfigInMemory(config: ProjectConfiguration, frameNumber: number | null, fps: number | null, resolutionBase: XY<number> | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_project_config_in_memory", { config, frameNumber, fps, resolutionBase }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEditorMeta() : Promise<Result<RecordingMeta, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_editor_meta") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMicWaveforms() : Promise<Result<number[][], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_mic_waveforms") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSystemAudioWaveforms() : Promise<Result<number[][], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_system_audio_waveforms") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * A JPEG of the display track at the playhead, for the crop dialog to draw
 * on. Downscaled: the cropper maps interactions back to full display
 * dimensions, so the reference only has to be sharp enough to aim with.
 */
async getDisplayFrameForCropping(fps: number) : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_display_frame_for_cropping", { fps }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getClipThumbnail(recordingSegment: number, time: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_clip_thumbnail", { recordingSegment, time }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEditorProjectPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_editor_project_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPrettyName(prettyName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_pretty_name", { prettyName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async generateZoomSegmentsFromClicks() : Promise<Result<ZoomSegment[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_zoom_segments_from_clicks") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async generateKeyboardSegments(groupingThresholdMs: number, lingerDurationMs: number, showModifiers: boolean, showSpecialKeys: boolean) : Promise<Result<KeyboardTrackSegment[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_keyboard_segments", { groupingThresholdMs, lingerDurationMs, showModifiers, showSpecialKeys }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes the whole project directory and closes its editor window.
 */
async deleteEditorProject() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_editor_project") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportVideo(projectPath: string, progress: TAURI_CHANNEL<FramesRendered>, settings: ExportSettings, exportId: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_video", { projectPath, progress, settings, exportId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportVideoToFile(projectPath: string, progress: TAURI_CHANNEL<FramesRendered>, settings: ExportSettings, exportId: string, fileName: string, fileType: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_video_to_file", { projectPath, progress, settings, exportId, fileName, fileType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelExport(exportId: string) : Promise<boolean> {
    return await TAURI_INVOKE("cancel_export", { exportId });
},
async getExportEstimates(path: string, settings: ExportSettings) : Promise<Result<ExportEstimates, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_export_estimates", { path, settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * One frame rendered at the chosen export settings, as a base64 JPEG — what
 * the export dialog shows so quality choices can be judged before committing
 * to a full render.
 */
async generateExportPreview(frameTime: number, settings: ExportPreviewSettings) : Promise<Result<ExportPreviewResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_export_preview", { frameTime, settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async spikeBeginCapture(name: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("spike_begin_capture", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async spikeWriteChunk(chunk: number[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("spike_write_chunk", { chunk }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async spikeFinishCapture() : Promise<Result<SpikeResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("spike_finish_capture") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createScreenshotEditorInstance() : Promise<Result<SerializedScreenshotEditorInstance, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_screenshot_editor_instance") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateScreenshotConfig(config: ProjectConfiguration, save: boolean, revision: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_screenshot_config", { config, save, revision }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async prewarmScreenshotBackground(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("prewarm_screenshot_background", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async recognizeScreenshotText(region: ScreenshotOcrRegion) : Promise<Result<ScreenshotOcrResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("recognize_screenshot_text", { region }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renderScreenshotForExport() : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("render_screenshot_for_export") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renderScreenshotProjectForExport(path: string) : Promise<Result<ScreenshotProjectExport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("render_screenshot_project_for_export", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rust is the only thing that ever measures a `TextContent` — an annotation
 * editor calls this on commit (not per keystroke; that policy is
 * `plans/text-engine/004`'s) and paints the returned `fragments` verbatim,
 * never re-measuring the text itself. `constraint.anchor_height` is the
 * capture's own content-rect height for an annotation, matching the
 * px@1080 convention `RunStyle::font_size` already uses.
 */
async measureText(content: TextContent, constraint: Constraint) : Promise<Result<TextLayoutResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("measure_text", { content, constraint }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The exact bytes of the face named by `id` (one of `measure_text`'s
 * returned `faces`), for the webview to register as a `FontFace` and paint
 * with directly — rather than resolving `font_family` itself, which is only
 * pinned correctly for the three CSS generics (`layers/mod.rs`'s
 * `new_font_system`), not for an arbitrary installed family name.
 */
async fontFaceBytes(id: FaceId) : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("font_face_bytes", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every family the shaping engine can resolve right now — the system scan
 * plus anything already downloaded. The picker's "available" list.
 */
async listFontFamilies() : Promise<FontFamily[]> {
    return await TAURI_INVOKE("list_font_families");
},
/**
 * Google's catalogue, for the picker's browse-and-search half. Cached to
 * `<app data>/fonts/catalog.json` on first success, and served from there
 * when the network is unavailable — a picker that empties itself offline
 * would be worse than one showing a slightly stale list.
 */
async googleFontCatalog() : Promise<Result<GoogleFont[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("google_font_catalog") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Downloads one Google family and loads it into the shaping engine, so it
 * becomes usable everywhere a system font is. Returns the family names the
 * downloaded file actually contained — normally just the one asked for.
 * 
 * Idempotent: a family already on disk is loaded from there rather than
 * re-fetched.
 */
async installGoogleFont(family: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_google_font", { family }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async doPermissionsCheck(initialCheck: boolean) : Promise<OSPermissionsCheck> {
    return await TAURI_INVOKE("do_permissions_check", { initialCheck });
},
async openPermissionSettings(permission: OSPermission) : Promise<void> {
    await TAURI_INVOKE("open_permission_settings", { permission });
},
async requestPermission(permission: OSPermission) : Promise<void> {
    await TAURI_INVOKE("request_permission", { permission });
},
async listCameras() : Promise<CameraInfo[]> {
    return await TAURI_INVOKE("list_cameras");
},
async listAudioDevices() : Promise<string[]> {
    return await TAURI_INVOKE("list_audio_devices");
},
async getCameraFormats(deviceId: string) : Promise<CameraWithFormats | null> {
    return await TAURI_INVOKE("get_camera_formats", { deviceId });
},
async getMicrophoneInfo(name: string) : Promise<MicrophoneInfo | null> {
    return await TAURI_INVOKE("get_microphone_info", { name });
},
async getDevicesSnapshot() : Promise<DevicesUpdated> {
    return await TAURI_INVOKE("get_devices_snapshot");
},
/**
 * Copies `source` into a new studio project so the editor can open it.
 * Returns the project directory.
 */
async importVideo(source: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_video", { source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Copies `source` into the screenshots library and writes its sidecar.
 * Returns the path of the imported copy.
 */
async importScreenshot(source: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_screenshot", { source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listRecordings() : Promise<([string, RecordingMetaWithMetadata])[]> {
    return await TAURI_INVOKE("list_recordings");
},
async listScreenshots() : Promise<([string, ScreenshotMetaWithMetadata])[]> {
    return await TAURI_INVOKE("list_screenshots");
},
/**
 * Off the main thread: the platform collectors query GPU adapters and probe
 * encoders, which is slow enough to stutter the window if run inline.
 */
async getSystemDiagnostics() : Promise<DiagnosticGroup[]> {
    return await TAURI_INVOKE("get_system_diagnostics");
},
/**
 * Absolute path of the directory the app writes logs to, so the Feedback page
 * can reveal it in the file manager. Cap uploads logs to its own servers;
 * Quiro has no backend, so the user gets the folder instead.
 */
async getLogsDir() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_logs_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDefaultExcludedWindows() : Promise<WindowExclusion[]> {
    return await TAURI_INVOKE("get_default_excluded_windows");
},
async setRecordingMode(mode: RecordingMode) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_recording_mode", { mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWindowIcon(windowId: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_window_icon", { windowId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Current cursor target, for overlays that mounted after the last emit.
 */
async getTargetUnderCursor() : Promise<TargetUnderCursor | null> {
    return await TAURI_INVOKE("get_target_under_cursor");
},
async displayInformation(displayId: string) : Promise<Result<DisplayInformation, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("display_information", { displayId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async focusWindow(windowId: WindowId) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("focus_window", { windowId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openTargetSelectOverlays(focusedTarget: ScreenCaptureTarget | null, specificDisplayId: string | null, targetMode: RecordingTargetMode | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_target_select_overlays", { focusedTarget, specificDisplayId, targetMode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeTargetSelectOverlays() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_target_select_overlays") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setFakeWindowBounds(name: string, bounds: LogicalBounds) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_fake_window_bounds", { name, bounds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeFakeWindow(name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_fake_window", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async performHapticFeedback(pattern: HapticPattern | null, time: HapticPerformanceTime | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("perform_haptic_feedback", { pattern, time }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if system audio capture is supported on the current platform and OS version.
 * On macOS, system audio capture requires macOS 13.0 or later.
 * On Windows/Linux, this may have different requirements.
 */
async isSystemAudioCaptureSupported() : Promise<boolean> {
    return await TAURI_INVOKE("is_system_audio_capture_supported");
},
async setTheme(theme: AppTheme) : Promise<void> {
    await TAURI_INVOKE("set_theme", { theme });
},
async positionTrafficLights(controlsInset: [number, number] | null) : Promise<void> {
    await TAURI_INVOKE("position_traffic_lights", { controlsInset });
},
async setTeleprompterWindowLevel(alwaysOnTop: boolean) : Promise<void> {
    await TAURI_INVOKE("set_teleprompter_window_level", { alwaysOnTop });
},
async setTeleprompterWindowOpacity(opacity: number) : Promise<void> {
    await TAURI_INVOKE("set_teleprompter_window_opacity", { opacity });
},
async refreshWindowContentProtection() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_window_content_protection") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setWindowTransparent(value: boolean) : Promise<void> {
    await TAURI_INVOKE("set_window_transparent", { value });
},
async showWindow(window: ShowQuiroWindow) : Promise<void> {
    await TAURI_INVOKE("show_window", { window });
},
async isCameraWindowOpen() : Promise<boolean> {
    return await TAURI_INVOKE("is_camera_window_open");
},
async setMicInput(label: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_mic_input", { label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setCameraInput(id: DeviceOrModelID | null, skipCameraWindow: boolean | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_camera_input", { id, skipCameraWindow }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCameraPreviewState() : Promise<Result<CameraPreviewState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_camera_preview_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * `frame_aspect` is the live camera's width/height, so Full shape can widen
 * the window to the camera's own aspect instead of assuming 16:9. Only the
 * frontend knows it on the WS path (it decodes the frames); `None` is fine
 * and falls back to 16:9.
 */
async setCameraPreviewState(previewState: CameraPreviewState, frameAspect: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_camera_preview_state", { previewState, frameAspect }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persists where the user dragged the camera bubble to, both globally and
 * keyed by monitor name — the window-open path prefers the per-monitor entry
 * so an unplugged/rearranged display doesn't strand the window off-screen
 * (see windows/variants/camera.rs).
 */
async setCameraWindowPosition(x: number, y: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_camera_window_position", { x, y }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ignoreCameraWindowPosition(durationMs: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ignore_camera_window_position", { durationMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeCameraWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_camera_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
audioInputLevelChange: AudioInputLevelChange,
currentRecordingChanged: CurrentRecordingChanged,
devicesUpdated: DevicesUpdated,
editorStateChanged: EditorStateChanged,
frameLayoutEvent: FrameLayoutEvent,
newNotification: NewNotification,
newScreenshotAdded: NewScreenshotAdded,
onEscapePress: OnEscapePress,
recordingEvent: RecordingEvent,
renderFrameEvent: RenderFrameEvent,
requestScreenCapturePrewarm: RequestScreenCapturePrewarm,
requestSetTargetMode: RequestSetTargetMode,
requestStartRecording: RequestStartRecording,
targetUnderCursor: TargetUnderCursor
}>({
audioInputLevelChange: "audio-input-level-change",
currentRecordingChanged: "current-recording-changed",
devicesUpdated: "devices-updated",
editorStateChanged: "editor-state-changed",
frameLayoutEvent: "frame-layout-event",
newNotification: "new-notification",
newScreenshotAdded: "new-screenshot-added",
onEscapePress: "on-escape-press",
recordingEvent: "recording-event",
renderFrameEvent: "render-frame-event",
requestScreenCapturePrewarm: "request-screen-capture-prewarm",
requestSetTargetMode: "request-set-target-mode",
requestStartRecording: "request-start-recording",
targetUnderCursor: "target-under-cursor"
})

/** user-defined constants **/



/** user-defined types **/

export type Annotation = { id: string; type: AnnotationType; x: number; y: number; width: number; height: number; strokeColor: string; strokeWidth: number; fillColor: string; opacity: number; rotation: number; text: string | null; 
/**
 * What this mask does. `None` on every non-mask annotation; required on a
 * mask. Shares [`MaskMode`] with the timeline's `MaskSegment` — one
 * taxonomy for one concept.
 */
maskMode?: MaskMode | null; 
/**
 * Effect strength in the mask contract's units, 1080p-relative, exactly
 * as `MaskSegment::amount`. Legacy configs stored this as
 * `maskLevel` in frame pixels, which meant something different at every
 * frame size; converted by
 * [`ProjectConfiguration::migrate_annotation_space`].
 */
maskAmount?: number | null; maskShape?: MaskShape | null; 
/**
 * 0..1 of the region's shorter axis. Ignored for
 * [`MaskMode::Redact`], which must stay hard-edged.
 */
maskFeather?: number | null; 
/**
 * Spotlight only: how far the area *outside* the region is darkened.
 */
maskDarkness?: number | null; 
/**
 * 0..1 of the region's shorter axis, for [`MaskShape::RoundedRect`].
 */
maskCornerRadius?: number | null; focus?: FocusConfig | null; arrowCurve?: ArrowCurve | null; arrowBend?: number | null; arrowStartHead?: ArrowHead | null; arrowEndHead?: ArrowHead | null; arrowHeadSize?: number | null; lineStyle?: LineStyle | null; arrowTaper?: boolean | null; 
/**
 * The tree representation of `text`, for `AnnotationType::Text`. `None`
 * until `migrate_annotation_space`'s third step wraps `text` and
 * `height` into it, which needs the capture size and so cannot happen
 * inside [`ProjectConfiguration::load`].
 */
textContent?: TextContent | null }
export type AnnotationType = "arrow" | "circle" | "rectangle" | "text" | "mask" | "focus"
export type AppTheme = "system" | "light" | "dark"
/**
 * Arrow-only shape/style. All optional on `Annotation`: absent reproduces the
 * original straight arrow with a single solid head. Geometry lives in the
 * frontend's `arrow.ts`; the renderer never draws annotations.
 */
export type ArrowCurve = "straight" | "quadratic" | "cubic" | "elbow"
export type ArrowHead = "none" | "arrow" | "triangle" | "circle" | "square"
export type AspectRatio = "wide" | "vertical" | "square" | "classic" | "tall"
export type Audio = { duration: number; sample_rate: number; channels: number; start_time: number }
export type AudioConfiguration = { mute: boolean; improve: boolean; micVolumeDb: number; micStereoMode: StereoMode; systemVolumeDb: number }
/**
 * Overlap-trim accounting captured by the recorder's audio gap tracker, persisted so the
 * editor can compensate for stale-startup audio drift from typed data instead of scraping
 * the recording log. See `cap-editor`'s `audio_timing_repair_offset`.
 */
export type AudioGapSummary = { 
/**
 * Total audio trimmed from overlapping frames over the whole recording, in milliseconds.
 */
total_overlap_trimmed_ms: number; 
/**
 * Startup-window trim used for stale-startup repair, excluding mid-recording trims.
 */
startup_overlap_trimmed_ms?: number; 
/**
 * Number of whole audio frames dropped because they fully overlapped the committed timeline.
 */
overlap_dropped_frames: number; 
/**
 * Subset of `overlap_dropped_frames` that dropped within the first few frames — the
 * signature of a stale buffered burst at capture start.
 */
startup_overlap_drops: number }
export type AudioInputLevelChange = number
export type AudioMeta = { path: string; start_time?: number | null; device_id?: string | null; gap_summary?: AudioGapSummary | null }
/**
 * A timeline-positioned audio clip (background music or imported audio).
 * 
 * Unlike the recording's mic/system audio (which is keyed to recording clips),
 * these segments live in output/timeline time exactly like zoom/text/mask
 * segments. `path` is resolved relative to the project directory so projects
 * stay portable when moved.
 */
export type AudioTrackSegment = { start: number; end: number; track?: number; path: string; name?: string | null; enabled?: boolean; 
/**
 * Offset into the source audio file (seconds) at which playback begins.
 */
trimStart?: number; volumeDb?: number; fadeIn?: number; fadeOut?: number; 
/**
 * Source duration in seconds, persisted so the UI can clamp resizing
 * without re-decoding the file.
 */
duration?: number | null }
export type BackgroundBlurConfig = { mode: BackgroundBlurMode }
export type BackgroundBlurMode = "off" | "light" | "heavy"
export type BackgroundConfiguration = { source: BackgroundSource; blur: number; padding: number; rounding: number; roundingType: CornerStyle; inset: number; crop: Crop | null; 
/**
 * Normalized (0-1) center of the display rect in output-frame space.
 * `None` keeps the display centered. When a frame is active this is the
 * center of the framed card (chrome included), not the bare video.
 */
displayPosition: XY<number> | null; shadow: number; advancedShadow: ShadowConfiguration | null; border: BorderConfiguration | null; 
/**
 * Decorative frame around the recording. `None` (or `FrameStyle::None`)
 * renders the bare video exactly as before the feature existed.
 */
frame: FrameConfiguration | null; 
/**
 * 3D tilt of the card. `None` renders it perfectly flat, pixel-identical
 * to before this field existed — screenshots are the only surface that
 * ever sets it; video and camera layers never see anything else.
 */
perspective: PerspectiveConfiguration | null; 
/**
 * Film-grain noise laid over the whole background, whatever the source
 * (colour, gradient, wallpaper, imported image). `None`/`0` renders no
 * noise, byte-identical to before this field existed. When unset the
 * renderer falls back to a gradient source's own `noise_intensity`.
 */
noiseIntensity?: number | null; 
/**
 * Grain size for `noise_intensity`. Defaults to `3.0` when noise is on.
 */
noiseScale?: number | null; 
/**
 * Free placement of the capture inside the canvas: drag, uniform scale,
 * in-plane rotation. `None` renders exactly the layout-derived placement
 * this field did not exist to change.
 * 
 * Its offset composes with [`Self::display_position`] rather than
 * replacing it: that one is an absolute centre clamped into the frame,
 * this one is a free delta on top, so a layer may leave the canvas
 * entirely and be clipped.
 */
displayTransform?: LayerTransform | null }
export type BackgroundSource = { type: "wallpaper"; path: string | null } | { type: "image"; path: string | null } | { type: "color"; value: [number, number, number]; alpha?: number } | { type: "gradient"; from: [number, number, number]; to: [number, number, number]; angle?: number; noise_intensity?: number | null; noise_scale?: number | null; animated?: boolean | null; animation_speed?: number | null }
export type BorderConfiguration = { enabled: boolean; width: number; color: [number, number, number]; opacity: number }
export type Camera = { hide: boolean; mirror: boolean; position: CameraPosition; 
/**
 * Normalized (0-1) center of the camera rect in output-frame space.
 * Overrides `position` when set.
 */
manualPosition: XY<number> | null; size: number; zoomSize: number | null; rounding: number; shadow: number; advancedShadow: ShadowConfiguration | null; shape: CameraShape; roundingType: CornerStyle; scaleDuringZoom?: number; backgroundBlur?: BackgroundBlurConfig }
export type CameraDeviceSettings = { width: number | null; height: number | null; frameRate: number | null }
export type CameraFormatInfo = { width: number; height: number; frameRate: number }
export type CameraInfo = { device_id: string; model_id: ModelIDType | null; display_name: string }
export type CameraPosition = { x: CameraXPosition; y: CameraYPosition }
export type CameraPreviewShape = "round" | "square" | "full"
export type CameraPreviewState = { size: number; shape: CameraPreviewShape; mirrored: boolean; background_blur?: BackgroundBlurMode }
export type CameraShape = "square" | "source"
export type CameraWithFormats = { deviceId: string; displayName: string; modelId: string | null; formats: CameraFormatInfo[]; bestFormat: CameraFormatInfo | null }
export type CameraXPosition = "left" | "center" | "right"
export type CameraYPosition = "top" | "bottom"
export type CaptionSegment = { id: string; start: number; end: number; text: string; words?: CaptionWord[] }
export type CaptionSettings = { enabled: boolean; font: string; size: number; color: string; backgroundColor: string; backgroundOpacity: number; position: string; italic: boolean; fontWeight: number; outline: boolean; outlineColor: string; exportWithSubtitles: boolean; highlightColor: string; fadeDuration: number; lingerDuration: number; wordTransitionDuration: number; activeWordHighlight: boolean; manualPosition: XY<number> | null; preset: string; animation: string; highlightStyle: string; uppercase: boolean }
export type CaptionTrackSegment = { id: string; start: number; end: number; text: string; words?: CaptionWord[]; fadeDurationOverride?: number | null; lingerDurationOverride?: number | null; positionOverride?: string | null; colorOverride?: string | null; backgroundColorOverride?: string | null; fontSizeOverride?: number | null }
export type CaptionWord = { text: string; start: number; end: number }
export type CaptionsData = { segments: CaptionSegment[]; settings: CaptionSettings; 
/**
 * When true, `segments` are stored in source/recording time and the
 * rendered `timeline.caption_segments` are derived by projecting them
 * through the current edit list, so captions stay aligned to their spoken
 * content as clips are trimmed, deleted, reordered, or inserted. Legacy
 * projects (false) stored segments in already-edited output time and are
 * migrated to source time on first load.
 */
sourceTimed?: boolean }
export type CaptureDisplay = { id: DisplayId; name: string; refresh_rate: number }
export type CaptureDisplayWithThumbnail = { id: string; name: string; refresh_rate: number; thumbnail: string | null }
export type CaptureWindow = { id: WindowId; owner_name: string; name: string; bounds: LogicalBounds; refresh_rate: number; bundle_identifier: string | null }
export type CaptureWindowWithThumbnail = { id: string; owner_name: string; name: string; bounds: LogicalBounds; refresh_rate: number; thumbnail: string | null; app_icon: string | null; bundle_identifier: string | null }
export type ClickSpringConfig = { tension: number; mass: number; friction: number }
export type ClipConfiguration = { index: number; offsets: ClipOffsets; 
/**
 * Whether `offsets` were computed automatically (recording start-time
 * alignment + device sync calibration) rather than entered by the user.
 * Cleared by the editor UI once the user edits an offset.
 */
offsetsAutoCalculated?: boolean }
export type ClipOffsets = { camera?: number; mic?: number; system_audio?: number }
export type ClipSpeedAudioMode = "mute" | "maintainPitch" | "matchSpeed"
export type ClipTransition = { segmentIndex: number; type: ClipTransitionType; duration: number }
export type ClipTransitionType = "cross-fade" | "fade-through-black"
/**
 * What a layout is measured against. Font sizes are always px@1080 of
 * `anchor_height` — see `RunStyle::font_size` in `quiro-project`.
 */
export type Constraint = { anchorHeight: number; 
/**
 * Box width in output px. Ignored for `GrowType::AutoWidth`.
 */
width: number; 
/**
 * Box height in output px. Ignored unless `GrowType::Fixed`.
 */
height: number }
export type CornerStyle = "squircle" | "rounded"
export type Crop = { position: XY<number>; size: XY<number> }
export type CurrentRecordingChanged = null
export type CursorAnimationStyle = "slow" | "smooth" | "mellow" | "fast" | "custom"
export type CursorConfiguration = { hide: boolean; hideWhenIdle: boolean; hideWhenIdleDelay: number; size: number; type: CursorType; animationStyle: CursorAnimationStyle; tension: number; mass: number; friction: number; raw: boolean; motionBlur: number; useSvg: boolean; rotationAmount?: number; baseRotation?: number; clickSpring?: ClickSpringConfig | null; stopMovementInLastSeconds?: number | null }
export type CursorMeta = { imagePath: string; hotspot: XY<number>; shape?: string | null }
export type CursorType = "auto" | "pointer" | "circle"
export type Cursors = { [key in string]: string } | { [key in string]: CursorMeta }
export type DeviceOrModelID = { DeviceID: string } | { ModelID: ModelIDType }
export type DevicesUpdated = { cameras: CameraInfo[]; microphones: string[]; permissions: OSPermissionsCheck }
export type DiagnosticEntry = { label: string; value: string; 
/**
 * Marks a value the user probably needs to act on — a missing permission,
 * software rendering, no hardware encoder. The page styles these.
 */
warning?: boolean }
export type DiagnosticGroup = { title: string; entries: DiagnosticEntry[] }
export type DisplayId = string
export type DisplayInformation = { name: string | null; physical_size: PhysicalSize | null; logical_size: LogicalSize | null; logical_bounds: LogicalBounds | null; refresh_rate: string }
export type EditorPreviewQuality = "quarter" | "half" | "full"
export type EditorStateChanged = { playhead_position: number }
export type ExportCompression = "Maximum" | "Social" | "Web" | "Potato"
export type ExportEstimates = { duration_seconds: number; estimated_time_seconds: number; estimated_size_mb: number }
export type ExportPreviewResult = { jpeg_base64: string; estimated_size_mb: number; actual_width: number; actual_height: number; total_frames: number }
export type ExportPreviewSettings = { fps: number; resolution_base: XY<number>; compression_bpp: number; cursor_only?: boolean }
export type ExportSettings = ({ format: "Mp4" } & Mp4ExportSettings) | ({ format: "Gif" } & GifExportSettings) | ({ format: "Mov" } & MovExportSettings)
/**
 * A face identity that can cross a process boundary. `cosmic_text::fontdb::ID`
 * can't: it has no `Serialize`/`specta::Type` impl, and its internal
 * slotmap key is private with no public constructor from a raw integer
 * (only `ID::dummy()`) — a value the frontend sent back could never be
 * turned back into a real `fontdb::ID`. This wraps a `FaceRegistry`-assigned
 * integer instead; two `FaceId`s are equal iff they name the same face in
 * this crate's one shared `FontSystem`. `plans/text-engine/003` ships the
 * bytes this id names, via `crate::face_bytes`.
 */
export type FaceId = number
export type FocusConfig = { x: number; y: number; radiusX: number; radiusY: number; 
/**
 * Degrees, clockwise. Lets the plane of focus follow a diagonal subject.
 */
rotation: number; shape: FocusShape; blur: number; depth: number; lens: number; 
/**
 * Asymmetry multipliers: content above the focus reads as further away,
 * below as nearer, so a composition can defocus one side harder. `1.0`
 * each side is symmetric.
 */
nearBlur: number; farBlur: number }
/**
 * Cinematic depth of field over the screenshot: an elliptical plane of focus,
 * with blur growing continuously with distance from it — a circle-of-confusion
 * approximation rather than a sharp-inside/blurred-outside mask. Applies to the
 * screenshot only; the composition's background is never touched.
 * 
 * The region is normalized to the screenshot (0..1 on each axis) so the effect
 * is resolution-independent and survives padding, crop and aspect-ratio changes
 * that move the screenshot within the frame.
 * 
 * `blur`, `depth` and `lens` are the user-facing dials (0-100); the shader
 * derives max circle-of-confusion, falloff curve and bokeh highlight strength
 * from them, so no lens terminology leaks into the UI.
 * Outline of the plane of focus. An ellipse is the lens-native shape; a
 * rectangle suits UI screenshots, where the subject is usually a panel, a
 * toolbar or a dialog rather than a round object.
 */
export type FocusShape = "ellipse" | "rectangle"
/**
 * A font family the user can pick, as the shaping engine sees it — this is
 * the authoritative list, because a family that isn't in here is one
 * cosmic-text cannot shape with, whatever the webview might manage to
 * render as a preview.
 */
export type FontFamily = { name: string; 
/**
 * From `fontdb`'s own per-face flag. The only categorisation the system
 * font database actually carries — serif vs. sans-serif is not
 * recorded, so the picker only groups Google families (whose catalogue
 * does carry a category) beyond this.
 */
monospaced: boolean }
/**
 * One contiguous, same-style piece of a visual (wrapped) line: the
 * intersection of a cosmic-text `LayoutRun` with one of `TextContent`'s
 * style runs. Fully resolved — a painter needs nothing else, and never
 * re-measures.
 */
export type Fragment = { 
/**
 * Index into `TextRoot`'s flattened paragraph list.
 */
paragraph: number; 
/**
 * Index into that paragraph's `children` (its style runs).
 */
run: number; x: number; 
/**
 * Baseline, not top — matches `cosmic_text::LayoutRun::line_y` and the
 * SVG `dominant-baseline` convention the frontend painter already
 * assumes for `position-data`-shaped output.
 */
y: number; width: number; height: number; 
/**
 * The paragraph's bidi direction. cosmic-text runs bidi regardless of
 * whether a direction control exists in the UI, so this is correct even
 * though nothing yet lets a user choose it. A painter anchors an RTL
 * fragment at `x + width`, not `x`.
 */
rtl: boolean; text: string; 
/**
 * The face this fragment's glyphs actually shaped with — which may
 * differ from the run's requested `font_family` after fallback
 * substitution. Taken from the fragment's first glyph; a fallback
 * substitution mid-fragment (e.g. an emoji inside a Latin run) is not
 * split into its own fragment.
 */
fontFace: FaceId; fontSize: number; fontWeight: number; italic: boolean; color: string; decoration: TextDecoration }
export type FrameConfiguration = { style: FrameStyle; theme: FrameTheme; 
/**
 * Text shown in the browser style's URL pill.
 */
url: string; 
/**
 * Text shown in the macOS window style's title bar.
 */
title: string }
/**
 * Rendered display/camera placement of the latest preview frame, in
 * output-frame pixels — lets on-canvas overlays line up with what was
 * actually rendered.
 */
export type FrameLayoutEvent = { display: [number, number, number, number]; camera: [number, number, number, number] | null; output_width: number; output_height: number }
/**
 * Decorative frame drawn around the screen recording (browser window,
 * macOS window, MacBook bezel, ...). The video is inset inside the frame's
 * chrome; the framed card as a whole follows padding / position / zoom
 * exactly like the bare video does today.
 */
export type FrameStyle = 
/**
 * No frame: the video renders bare, exactly as before this feature.
 */
"none" | 
/**
 * A macOS window title bar with traffic-light buttons.
 */
"macOS" | 
/**
 * A Windows 11 window title bar with minimize/maximize/close controls.
 */
"windows" | 
/**
 * A browser toolbar: traffic lights plus a centered URL pill.
 */
"browser" | 
/**
 * A MacBook mockup: black bezel, aluminum body and deck.
 */
"macbook"
export type FrameTheme = "dark" | "light"
export type FramesRendered = { rendered_count: number; total_frames: number }
export type GeneralSettingsStore = { instanceId?: string; hideDockIcon?: boolean; enableNotifications?: boolean; disableAutoOpenLinks?: boolean; hasCompletedStartup?: boolean; theme?: AppTheme; lastVersion?: string | null; windowTransparency?: boolean; postStudioRecordingBehaviour?: PostStudioRecordingBehaviour; mainWindowRecordingStartBehaviour?: MainWindowRecordingStartBehaviour; custom_cursor_capture2?: boolean; recordingCountdown?: number | null; enableNativeCameraPreview: boolean; autoZoomOnClicks?: boolean; captureKeyboardEvents?: boolean; postDeletionBehaviour?: PostDeletionBehaviour; excludedWindows?: WindowExclusion[]; instantModeMaxResolution?: number; defaultProjectNameTemplate?: string | null; crashRecoveryRecording?: boolean; maxFps?: number; transcriptionHints?: string[]; editorPreviewQuality?: EditorPreviewQuality; studioRecordingQuality?: StudioRecordingQuality; mainWindowPosition?: WindowPosition | null; cameraWindowPosition?: WindowPosition | null; cameraWindowPositionsByMonitorName?: { [key in string]: WindowPosition }; hasCompletedOnboarding?: boolean; outOfProcessMuxer?: boolean; recordingsPath?: string | null; 
/**
 * Custom recordings folders that were used before; recordings left in
 * them stay visible in the library. Most recent last.
 */
previousRecordingsPaths?: string[]; 
/**
 * App version at which camera background blur was disabled after a crash
 * was attributed to the blur pipeline; `None` means blur is allowed.
 * Cleared automatically when the app version changes (one retry per
 * update, since a new ort/wgpu/driver stack may have fixed the crash).
 */
cameraBlurDisabledByCrash?: string | null }
export type GifExportSettings = { fps: number; resolution_base: XY<number>; quality: GifQuality | null }
export type GifQuality = { 
/**
 * Encoding quality from 1-100 (default: 90)
 */
quality: number | null; 
/**
 * Whether to prioritize speed over quality (default: false)
 */
fast: boolean | null }
export type GlideDirection = "none" | "left" | "right" | "up" | "down"
export type GoogleFont = { family: string; 
/**
 * `sans-serif`, `serif`, `display`, `handwriting` or `monospace`, as
 * Google categorises it — the picker groups by this.
 */
category: string }
/**
 * Width and height from content (no wrapping), width from the box height
 * from content, or both from the box with content clipping. See
 * `plans/text-engine/000-text-content-model.md`.
 */
export type GrowType = "autoWidth" | "autoHeight" | "fixed"
export type HapticPattern = "alignment" | "levelChange" | "generic"
export type HapticPerformanceTime = "default" | "now" | "drawCompleted"
export type Hotkey = { code: string; meta: boolean; ctrl: boolean; alt: boolean; shift: boolean }
export type HotkeyAction = "startStudioRecording" | "startInstantRecording" | "stopRecording" | "restartRecording" | "togglePauseRecording" | "cycleRecordingMode" | "openRecordingPicker" | "openRecordingPickerDisplay" | "openRecordingPickerWindow" | "openRecordingPickerArea" | "screenshotDisplay" | "screenshotWindow" | "screenshotArea" | "other"
export type HotkeysConfiguration = { show: boolean }
export type HotkeysStore = { hotkeys: { [key in HotkeyAction]: Hotkey } }
export type InstantRecordingMeta = { recording: boolean } | { error: string } | { fps: number; sample_rate: number | null }
export type KeyPressDisplay = { key: string; timeOffset: number }
export type KeyboardData = { settings: KeyboardSettings }
export type KeyboardSettings = { enabled: boolean; font: string; size: number; color: string; backgroundColor: string; backgroundOpacity: number; position: string; fontWeight: number; fadeDuration: number; lingerDuration: number; groupingThresholdMs: number; showModifiers: boolean; showSpecialKeys: boolean; uppercase: boolean }
export type KeyboardTrackSegment = { id: string; start: number; end: number; displayText: string; keys?: KeyPressDisplay[]; fadeDurationOverride?: number | null; positionOverride?: string | null; colorOverride?: string | null; backgroundColorOverride?: string | null; fontSizeOverride?: number | null; uppercaseOverride?: boolean | null }
/**
 * A composited layer's placement relative to the canvas it lives in.
 * 
 * The canvas is a fixed viewport, not a bounding box: it owns the output size
 * and the background, and whatever a layer puts outside it is clipped by the
 * render target rather than growing the frame. This is how far a layer has
 * been moved, scaled and spun inside that viewport, measured from wherever
 * the layout put it.
 * 
 * `offset` is a fraction of the canvas rather than pixels, so a composition
 * authored against the editor's preview survives an export at any other
 * resolution. Rotation is deliberately separate from the rect: the renderer
 * carries it in the card homography, which leaves `offset` and `scale`
 * describing an axis-aligned rect that layout, hit-testing and the annotation
 * anchor can all still reason about.
 */
export type LayerTransform = { 
/**
 * Displacement from the laid-out position, as a fraction of canvas
 * width and height. Zero leaves the layer where layout put it.
 */
offset: XY<number>; 
/**
 * Uniform scale about [`Self::scale_origin`].
 */
scale: number; 
/**
 * The point the scale is anchored at, as a fraction of the layer's own
 * width and height. `(0.5, 0.5)` — the default — scales about the
 * centre, which is what this transform did before the field existed, so
 * an untouched project is bit-identical.
 * 
 * This is what lets the Zoom control magnify a corner of the screenshot
 * rather than always pushing outward from the middle: the point under
 * the focal handle is the one that stays put.
 */
scaleOrigin: XY<number>; 
/**
 * In-plane rotation about the layer's own centre, in degrees.
 */
rotation: number }
export type LineStyle = "solid" | "dashed" | "dotted"
export type LogicalBounds = { position: LogicalPosition; size: LogicalSize }
export type LogicalPosition = { x: number; y: number }
export type LogicalSize = { width: number; height: number }
export type MainWindowRecordingStartBehaviour = "close" | "minimise"
export type MaskKeyframes = { position?: MaskVectorKeyframe[]; size?: MaskVectorKeyframe[]; intensity?: MaskScalarKeyframe[] }
/**
 * What a mask does to the region it covers.
 * 
 * Replaces the old split between a `MaskKind` of `sensitive`/`highlight` —
 * which was a *category*, not a mode — and a discriminant smuggled into the
 * effect amount by adding 1000 to it. One enum, readable in the JSON,
 * checkable by the compiler.
 */
export type MaskMode = 
/**
 * Separable gaussian. Obscures; does **not** guarantee irreversibility —
 * a gaussian is deconvolvable in principle.
 */
"blur" | 
/**
 * Nearest-neighbour block averaging. Also not irreversible: each block
 * leaks the average of the pixels under it.
 */
"pixelate" | 
/**
 * Opaque fill. The only mode safe for credentials — no source pixel
 * survives inside the region.
 */
"redact" | 
/**
 * Darkens everything *outside* the region rather than obscuring inside
 * it. This is what the old `highlight` kind always did; the name now says
 * so, since "highlight" reads as drawing *on* the region.
 */
"spotlight"
export type MaskScalarKeyframe = { time: number; value: number }
export type MaskSegment = { start: number; end: number; track?: number; enabled?: boolean; 
/**
 * What the mask does. Legacy configs carry `maskType` + `pixelation`
 * instead and are converted by
 * [`ProjectConfiguration::migrate_mask_model`].
 */
mode?: MaskMode; 
/**
 * Effect strength in the contract's units (see `mask-effects.json`),
 * 1080p-relative and scaled by output height at render time. Meaningless
 * for [`MaskMode::Spotlight`], which uses `darkness` instead.
 */
amount?: number; shape?: MaskShape; center: XY<number>; size: XY<number>; feather?: number; opacity?: number; darkness?: number; fadeDuration?: number; keyframes?: MaskKeyframes }
/**
 * The region's outline. Rendering for the non-rect variants lands with the
 * shader rewrite in plan 004; the field exists now so that change is not
 * another migration.
 */
export type MaskShape = "rect" | "ellipse" | "roundedRect"
export type MaskVectorKeyframe = { time: number; x: number; y: number }
export type MicrophoneDeviceSettings = { sampleRate: number | null; channels: number | null }
export type MicrophoneFormatInfo = { sampleRate: number; channels: number }
export type MicrophoneInfo = { name: string; sampleRate: number; channels: number; formats: MicrophoneFormatInfo[] }
export type ModelIDType = string
export type MovExportSettings = { fps: number; resolution_base: XY<number>; cursor_only?: boolean }
export type Mp4ExportSettings = { fps: number; resolution_base: XY<number>; compression: ExportCompression; custom_bpp: number | null; force_ffmpeg_decoder?: boolean; optimize_filesize?: boolean }
export type MultipleSegment = { display: VideoMeta; camera?: VideoMeta | null; mic?: AudioMeta | null; system_audio?: AudioMeta | null; cursor?: string | null; keyboard?: string | null }
export type MultipleSegments = { segments: MultipleSegment[]; cursors: Cursors; status?: StudioRecordingStatus | null }
export type NewNotification = { title: string; body: string; is_error: boolean }
/**
 * Emitted once a screenshot is fully written to disk, so an open library
 * view can refresh instead of polling for new files.
 */
export type NewScreenshotAdded = { path: string }
export type OSPermission = "screenRecording" | "camera" | "microphone" | "accessibility"
export type OSPermissionStatus = "notNeeded" | "empty" | "granted" | "denied"
export type OSPermissionsCheck = { screenRecording: OSPermissionStatus; microphone: OSPermissionStatus; camera: OSPermissionStatus; accessibility: OSPermissionStatus }
/**
 * Emitted when Escape is pressed while a target-select overlay is open. The
 * overlays are transparent, click-through-ish windows that may not hold
 * keyboard focus, so Escape is caught as a global shortcut in Rust (see
 * `WindowFocusManager::register_escape`) rather than as a DOM keydown.
 */
export type OnEscapePress = null
export type Paragraph = { align: TextAlign; 
/**
 * Multiplier, not px — matches cosmic-text's `Metrics::line_height`
 * convention that `quiro-text` will shape against.
 */
lineHeight: number; children: TextRun[] }
export type ParagraphSet = { children: Paragraph[] }
/**
 * Screenshot-editor rotation: tilts the card in 3D. Three angles and nothing
 * else — X and Y lean it out of the screen plane, Z spins it within that
 * plane — so the schema reads the way the panel's own X/Y/Z sliders do;
 * `quiro-rendering` turns them into the homography the shader wants.
 * 
 * There is deliberately no camera-distance dial. It used to be a 0-100
 * `depth` field, which asked people to tune a lens parameter to find out
 * what a tilt would look like; the renderer now fixes that distance
 * (`perspective::CAMERA_DISTANCE_PX`) so an angle is the only thing being
 * chosen. An old sidecar's `depth` is ignored on load rather than migrated:
 * serde skips the unknown field, and the tilt it described is re-rendered
 * at the fixed distance.
 */
export type PerspectiveConfiguration = { 
/**
 * Leaning away from (positive) or toward (negative) the viewer, degrees.
 */
tiltX: number; 
/**
 * Turning left (negative) or right (positive), degrees.
 */
tiltY: number; 
/**
 * In-plane spin, degrees. No foreshortening on its own.
 */
rotate: number }
export type PhysicalSize = { width: number; height: number }
export type Platform = "MacOS" | "Windows" | "Linux"
export type PostDeletionBehaviour = "doNothing" | "reopenRecordingWindow"
export type PostStudioRecordingBehaviour = "openEditor" | "showOverlay"
export type Preset = { name: string; config: ProjectConfiguration }
export type PresetsStore = { presets: Preset[]; default: number | null }
export type ProjectConfiguration = { aspectRatio: AspectRatio | null; background: BackgroundConfiguration; camera: Camera; audio: AudioConfiguration; cursor: CursorConfiguration; hotkeys: HotkeysConfiguration; timeline: TimelineConfiguration | null; captions: CaptionsData | null; keyboard: KeyboardData | null; clips: ClipConfiguration[]; annotations: Annotation[]; screenMotionBlur?: number; screenMovementSpring?: ScreenMovementSpring; 
/**
 * How text segment font sizes are interpreted. 0 (legacy): the renderer
 * multiplied `font_size` by `size.y / 0.2`, coupling glyph size to the
 * box. 1: `font_size` alone determines glyph size (1080p-relative);
 * legacy configs are migrated on load by baking the box factor into
 * `font_size`. The field-level default keeps old files at 0 while
 * `Default::default()` produces the current version.
 */
textSizeVersion?: number; 
/**
 * How annotation geometry is interpreted. 0 (legacy): `x`/`y`/`width`/
 * `height` are pixels in the rendered output frame — a frame whose size
 * and content offset are recomputed whenever padding, crop or aspect
 * ratio changes, so the stored numbers stop meaning what they meant.
 * 1: normalized 0..1 against the annotation's [`AnnotationAnchor`].
 * 
 * The field-level default keeps old files at 0 while `Default::default()`
 * produces the current version — the same arrangement as
 * [`Self::text_size_version`]. Migration is *not* performed here: it needs
 * the capture dimensions and the frame-layout maths, neither of which this
 * crate has. See `annotation_space::migrate`.
 */
annotationSpaceVersion?: number; 
/**
 * How mask segments are encoded. 0 (legacy): a `maskType` of
 * `sensitive`/`highlight` plus a `pixelation` float that smuggled
 * blur-vs-pixelate into its own value by adding 1000 to it. 1: an explicit
 * [`MaskMode`] and a plain `amount`. Migrated on load — see
 * [`Self::migrate_mask_model`].
 */
maskModelVersion?: number; 
/**
 * Whether text segments store their typography as a flat set of fields
 * (0, legacy) or as a [`TextContent`] tree (1). [`Annotation`] gets the
 * equivalent conversion as a step inside
 * [`Self::migrate_annotation_space`] instead of here: a legacy text
 * annotation's `height` only means "fraction of the capture's content
 * height" — what its `TextContent` font size is derived from — once
 * that migration has already normalized it. This field's migration has
 * no such dependency, so it runs inside [`Self::load`], the same as
 * [`Self::text_size_version`].
 */
textContentVersion?: number }
export type ProjectRecordingsMeta = { segments: SegmentRecordings[] }
export type RecordingEvent = { variant: "Countdown"; value: number } | { variant: "Started" } | { variant: "Stopped" } | { variant: "Paused" } | { variant: "Resumed" } | { variant: "Failed"; error: string } | { variant: "StartFailed"; error: string } | { variant: "InputLost"; input: RecordingInputKind } | { variant: "InputRestored"; input: RecordingInputKind }
/**
 * Which of the optional recording inputs a lifecycle event refers to. The
 * screen itself is never "lost" — only the devices attached alongside it can
 * disappear mid-recording.
 */
export type RecordingInputKind = "microphone" | "camera"
export type RecordingMeta = (StudioRecordingMeta | InstantRecordingMeta) & { platform?: Platform | null; pretty_name: string; sharing?: SharingMeta | null; upload?: UploadMeta | null }
export type RecordingMetaWithMetadata = { prettyName: string; sortTimeMillis: number; 
/**
 * The project directory. The row's other path points at a media file
 * inside it, which is what a preview or the editor wants — but revealing
 * or deleting a recording means the whole project, not one video.
 */
projectPath: string }
export type RecordingMode = "studio" | "instant" | "screenshot"
export type RecordingSettingsStore = { target: ScreenCaptureTarget | null; micName: string | null; cameraId: DeviceOrModelID | null; mode: RecordingMode | null; systemAudio: boolean; cameraDeviceSettings: { [key in string]: CameraDeviceSettings }; microphoneDeviceSettings: { [key in string]: MicrophoneDeviceSettings } }
export type RecordingTargetMode = "display" | "window" | "area" | "camera"
/**
 * Frontend -> backend: which frame the preview should show while paused.
 * An event rather than a command because it fires on every scrub tick.
 */
export type RenderFrameEvent = { frame_number: number; fps: number; resolution_base: XY<number> }
export type RequestScreenCapturePrewarm = { force?: boolean }
export type RequestSetTargetMode = { target_mode: RecordingTargetMode | null; display_id: string | null }
/**
 * Emitted when a hotkey asks for a recording to start. Unlike stop/pause,
 * starting needs a capture target, and the main window is the thing that knows
 * which one is currently selected — so this goes to the frontend rather than
 * calling `start_recording` with a guess.
 */
export type RequestStartRecording = { mode: RecordingMode }
export type RunStyle = { fontFamily: string; 
/**
 * Output px as if the anchor were 1080 tall — the same convention
 * [`TextSegment::font_size`] already uses. The anchor is the capture's
 * content rect for an [`Annotation`], the output frame for a
 * [`TextSegment`].
 */
fontSize: number; 
/**
 * `f32`, not cosmic-text's `u16` `Weight` — matches
 * [`TextSegment::font_size`]'s existing type exactly so migrating a
 * segment into this shape is a lossless move, not a lossy round. The
 * clamp to a valid weight belongs to the engine that shapes text, not
 * to the data model.
 */
fontWeight: number; italic: boolean; color: string; letterSpacing: number; decoration: TextDecoration; transform: TextTransform }
export type S3UploadMeta = { id: string }
export type SceneMode = "default" | "cameraOnly" | "hideCamera" | "splitScreen" | 
/**
 * Like [`SceneMode::SplitScreen`], but the screen and camera render as
 * padded, rounded, shadowed cards floating over the background instead
 * of full-bleed halves. Shares [`SplitLayout`] for per-pane pan/zoom.
 */
"floating"
export type SceneSegment = { start: number; end: number; mode?: SceneMode; splitLayout?: SplitLayout | null; transitionIn?: number; transitionOut?: number }
export type ScreenCaptureTarget = { variant: "window"; id: WindowId } | { variant: "display"; id: DisplayId } | { variant: "area"; screen: DisplayId; bounds: LogicalBounds } | { variant: "cameraOnly" }
export type ScreenMovementSpring = { stiffness: number; damping: number; mass: number }
export type ScreenshotMetaWithMetadata = { prettyName: string; sortTimeMillis: number }
export type ScreenshotOcrLine = { text: string; confidence: number | null; bounds: ScreenshotOcrRegion }
export type ScreenshotOcrRegion = { x: number; y: number; width: number; height: number }
export type ScreenshotOcrResult = { text: string; lines: ScreenshotOcrLine[]; engine: string }
export type ScreenshotProjectExport = { imageBytes: number[]; config: ProjectConfiguration; imageWidth: number; imageHeight: number }
export type SegmentRecordings = { display: Video; camera: Video | null; mic: Audio | null; system_audio: Audio | null }
export type SerializedEditorInstance = { framesSocketUrl: string; recordingDuration: number; savedProjectConfig: ProjectConfiguration; recordings: ProjectRecordingsMeta; path: string; prettyName: string }
export type SerializedScreenshotEditorInstance = { framesSocketUrl: string; 
/**
 * The capture's own layer. The preview stacks it over `frames_socket_url`
 * and places it with a CSS transform, so a drag never reaches the renderer.
 */
cardSocketUrl: string; path: string; config: ProjectConfiguration | null; prettyName: string; imageWidth: number; imageHeight: number }
export type ShadowConfiguration = { size: number; opacity: number; blur: number }
export type SharingMeta = { id: string; link: string; content_hash?: string | null }
export type ShowQuiroWindow = { Main: { init_target_mode: RecordingTargetMode | null } } | { Settings: { page: string | null } } | "RecordingsOverlay" | { WindowCaptureOccluder: { screen_id: DisplayId; 
/**
 * Display-relative bounds of the window/area being recorded — the
 * occluder blacks out everything on the display *outside* this
 * rect. `None` blacks out nothing (rather than the whole display),
 * since a target whose bounds couldn't be resolved is the one case
 * where covering the entire screen would be actively misleading.
 */
target_bounds: LogicalBounds | null } } | { TargetSelectOverlay: { display_id: DisplayId; target_mode: RecordingTargetMode | null } } | { CaptureArea: { screen_id: DisplayId } } | { Camera: { centered: boolean } } | { InProgressRecording: { countdown: number | null; capture_target?: ScreenCaptureTarget | null } } | "ModeSelect" | { ScreenshotEditor: { path: string } } | { Editor: { path: string } }
export type SingleSegment = { display: VideoMeta; camera?: VideoMeta | null; audio?: AudioMeta | null; cursor?: string | null }
export type SpikeResult = { path: string; chunks: number; bytes: number; seconds: number; 
/**
 * Throughput of the JS -> Rust hop alone, which is the part of the
 * pipeline this prototype can't measure from the webview side.
 */
megabytesPerSecond: number }
export type SplitLayout = { screenZoom: number; screenPosition: XY<number>; cameraZoom: number; cameraPosition: XY<number> }
export type StereoMode = "stereo" | "monoL" | "monoR"
export type StudioRecordingMeta = { segment: SingleSegment } | { inner: MultipleSegments }
export type StudioRecordingQuality = "compatibility" | "balanced" | "ultra"
export type StudioRecordingStatus = { status: "InProgress" } | { status: "NeedsRemux" } | { status: "Failed"; error: string } | { status: "Complete" }
export type TargetUnderCursor = { display_id: DisplayId | null; window: WindowUnderCursor | null }
export type TextAlign = "left" | "center" | "right" | "justify"
/**
 * Text content shared by [`Annotation`] (screenshot labels/callouts) and
 * [`TextSegment`] (video titles). Nothing in this crate lays this out —
 * that is the one job of `quiro-text` (`plans/text-engine/001`), which
 * nothing has built yet, so this type has no consumer until then.
 */
export type TextContent = { root: TextRoot; growType: GrowType; verticalAlign: VerticalAlign; 
/**
 * Outline drawn around each glyph, for legibility over arbitrary
 * screenshot content. `None` draws no outline.
 */
halo: TextHalo | null }
export type TextDecoration = "none" | "underline" | "lineThrough"
export type TextHalo = { width: number; color: string }
/**
 * `quiro_text::TextLayout` minus its `buffers` — those are cosmic-text's own
 * shaped glyph runs and never leave the process (`plans/text-engine/003`);
 * `fragments` is everything a frontend painter needs to draw the same
 * glyphs itself, in SVG on screen and Canvas2D at export.
 */
export type TextLayoutResult = { fragments: Fragment[]; width: number; height: number; 
/**
 * Every distinct face `fragments` references, in first-seen order — so
 * a caller can register each one exactly once (via `font_face_bytes`)
 * without first walking `fragments` itself to dedupe them.
 */
faces: FaceId[] }
/**
 * Always exactly one child in practice: paragraph sets carry no styling of
 * their own and exist only for structural parity with how paragraphs nest
 * inside them.
 */
export type TextRoot = { children: ParagraphSet[] }
export type TextRun = { text: string; style: RunStyle }
export type TextSegment = { start: number; end: number; track?: number; enabled?: boolean; content?: string; center?: XY<number>; size?: XY<number>; fontFamily?: string; fontSize?: number; fontWeight?: number; italic?: boolean; color?: string; fadeDuration?: number; 
/**
 * The tree representation. `None` until `migrate_text_content` wraps the
 * fields above into it — see [`ProjectConfiguration::text_content_version`].
 */
textContent?: TextContent | null }
export type TextTransform = "none" | "uppercase" | "lowercase" | "capitalize"
export type TimelineConfiguration = { segments: TimelineSegment[]; transitions: ClipTransition[]; zoomSegments: ZoomSegment[]; sceneSegments?: SceneSegment[]; maskSegments?: MaskSegment[]; textSegments?: TextSegment[]; captionSegments?: CaptionTrackSegment[]; keyboardSegments?: KeyboardTrackSegment[]; audioSegments?: AudioTrackSegment[] }
export type TimelineSegment = { recordingSegment?: number; timescale: number; start: number; end: number; name?: string | null; speedAudioMode?: ClipSpeedAudioMode | null }
export type UploadMeta = { state: "MultipartUpload"; video_id: string; file_path: string; pre_created_video: VideoUploadInfo; recording_dir: string } | { state: "SinglePartUpload"; video_id: string; recording_dir: string; file_path: string; screenshot_path: string } | { state: "SegmentUpload"; video_id: string; pre_created_video: VideoUploadInfo; recording_dir: string } | { state: "Failed"; error: string } | { state: "Complete" }
export type VerticalAlign = "top" | "center" | "bottom"
export type Video = { duration: number; width: number; height: number; fps: number; start_time: number }
export type VideoMeta = { path: string; fps?: number; start_time?: number | null; device_id?: string | null }
export type VideoUploadInfo = { id: string; link: string; config: S3UploadMeta }
export type WindowExclusion = { bundleIdentifier?: string | null; ownerName?: string | null; windowTitle?: string | null }
export type WindowId = string
export type WindowPosition = { x: number; y: number; displayId?: DisplayId | null }
export type WindowUnderCursor = { id: WindowId; app_name: string; bounds: LogicalBounds }
export type XY<T> = { x: T; y: T }
export type ZoomMode = "auto" | { manual: { x: number; y: number } }
export type ZoomSegment = { start: number; end: number; amount: number; mode: ZoomMode; glideDirection?: GlideDirection; glideSpeed?: number; instantAnimation?: boolean; edgeSnapRatio?: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
