// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async takeScreenshot(target: ScreenCaptureTarget | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("take_screenshot", { target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listCaptureDisplays() : Promise<CaptureDisplay[]> {
    return await TAURI_INVOKE("list_capture_displays");
},
async listCaptureWindows() : Promise<CaptureWindow[]> {
    return await TAURI_INVOKE("list_capture_windows");
},
async listDisplaysWithThumbnails() : Promise<CaptureDisplayWithThumbnail[]> {
    return await TAURI_INVOKE("list_displays_with_thumbnails");
},
async listWindowsWithThumbnails() : Promise<CaptureWindowWithThumbnail[]> {
    return await TAURI_INVOKE("list_windows_with_thumbnails");
},
async startRecording(captureTarget: ScreenCaptureTarget) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_recording", { captureTarget }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopRecording() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pauseRecording() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resumeRecording() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discardRecording() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discard_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restartRecording() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restart_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Recording-scoped mic mute. The feed keeps running at its normal cadence and
 * silence is written instead, so muting can't desync audio against video.
 * Returns the resulting state so the caller never has to guess.
 */
async setRecordingMicMuted(muted: boolean) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_recording_mic_muted", { muted }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createScreenshotEditorInstance() : Promise<Result<SerializedScreenshotEditorInstance, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_screenshot_editor_instance") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateScreenshotConfig(config: ProjectConfiguration, save: boolean, revision: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_screenshot_config", { config, save, revision }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async prewarmScreenshotBackground(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("prewarm_screenshot_background", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async recognizeScreenshotText(region: ScreenshotOcrRegion) : Promise<Result<ScreenshotOcrResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("recognize_screenshot_text", { region }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renderScreenshotForExport() : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("render_screenshot_for_export") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renderScreenshotProjectForExport(path: string) : Promise<Result<ScreenshotProjectExport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("render_screenshot_project_for_export", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async doPermissionsCheck(initialCheck: boolean) : Promise<OSPermissionsCheck> {
    return await TAURI_INVOKE("do_permissions_check", { initialCheck });
},
async openPermissionSettings(permission: OSPermission) : Promise<void> {
    await TAURI_INVOKE("open_permission_settings", { permission });
},
async requestPermission(permission: OSPermission) : Promise<void> {
    await TAURI_INVOKE("request_permission", { permission });
},
async listCameras() : Promise<CameraInfo[]> {
    return await TAURI_INVOKE("list_cameras");
},
async listAudioDevices() : Promise<string[]> {
    return await TAURI_INVOKE("list_audio_devices");
},
async getCameraFormats(deviceId: string) : Promise<CameraWithFormats | null> {
    return await TAURI_INVOKE("get_camera_formats", { deviceId });
},
async getMicrophoneInfo(name: string) : Promise<MicrophoneInfo | null> {
    return await TAURI_INVOKE("get_microphone_info", { name });
},
async getDevicesSnapshot() : Promise<DevicesUpdated> {
    return await TAURI_INVOKE("get_devices_snapshot");
},
async listRecordings() : Promise<([string, RecordingMetaWithMetadata])[]> {
    return await TAURI_INVOKE("list_recordings");
},
async listScreenshots() : Promise<([string, ScreenshotMetaWithMetadata])[]> {
    return await TAURI_INVOKE("list_screenshots");
},
async getDefaultExcludedWindows() : Promise<WindowExclusion[]> {
    return await TAURI_INVOKE("get_default_excluded_windows");
},
async setRecordingMode(mode: RecordingMode) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_recording_mode", { mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWindowIcon(windowId: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_window_icon", { windowId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Current cursor target, for overlays that mounted after the last emit.
 */
async getTargetUnderCursor() : Promise<TargetUnderCursor | null> {
    return await TAURI_INVOKE("get_target_under_cursor");
},
async displayInformation(displayId: string) : Promise<Result<DisplayInformation, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("display_information", { displayId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async focusWindow(windowId: WindowId) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("focus_window", { windowId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openTargetSelectOverlays(focusedTarget: ScreenCaptureTarget | null, specificDisplayId: string | null, targetMode: RecordingTargetMode | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_target_select_overlays", { focusedTarget, specificDisplayId, targetMode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeTargetSelectOverlays() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_target_select_overlays") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setFakeWindowBounds(name: string, bounds: LogicalBounds) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_fake_window_bounds", { name, bounds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeFakeWindow(name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_fake_window", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async performHapticFeedback(pattern: HapticPattern | null, time: HapticPerformanceTime | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("perform_haptic_feedback", { pattern, time }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if system audio capture is supported on the current platform and OS version.
 * On macOS, system audio capture requires macOS 13.0 or later.
 * On Windows/Linux, this may have different requirements.
 */
async isSystemAudioCaptureSupported() : Promise<boolean> {
    return await TAURI_INVOKE("is_system_audio_capture_supported");
},
async setTheme(theme: AppTheme) : Promise<void> {
    await TAURI_INVOKE("set_theme", { theme });
},
async positionTrafficLights(controlsInset: [number, number] | null) : Promise<void> {
    await TAURI_INVOKE("position_traffic_lights", { controlsInset });
},
async setTeleprompterWindowLevel(alwaysOnTop: boolean) : Promise<void> {
    await TAURI_INVOKE("set_teleprompter_window_level", { alwaysOnTop });
},
async setTeleprompterWindowOpacity(opacity: number) : Promise<void> {
    await TAURI_INVOKE("set_teleprompter_window_opacity", { opacity });
},
async refreshWindowContentProtection() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_window_content_protection") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setWindowTransparent(value: boolean) : Promise<void> {
    await TAURI_INVOKE("set_window_transparent", { value });
},
async showWindow(window: ShowQuiroWindow) : Promise<void> {
    await TAURI_INVOKE("show_window", { window });
},
async isCameraWindowOpen() : Promise<boolean> {
    return await TAURI_INVOKE("is_camera_window_open");
},
async setMicInput(label: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_mic_input", { label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setCameraInput(id: DeviceOrModelID | null, skipCameraWindow: boolean | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_camera_input", { id, skipCameraWindow }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCameraPreviewState() : Promise<Result<CameraPreviewState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_camera_preview_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * `frame_aspect` is the live camera's width/height, so Full shape can widen
 * the window to the camera's own aspect instead of assuming 16:9. Only the
 * frontend knows it on the WS path (it decodes the frames); `None` is fine
 * and falls back to 16:9.
 */
async setCameraPreviewState(previewState: CameraPreviewState, frameAspect: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_camera_preview_state", { previewState, frameAspect }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persists where the user dragged the camera bubble to, both globally and
 * keyed by monitor name — the window-open path prefers the per-monitor entry
 * so an unplugged/rearranged display doesn't strand the window off-screen
 * (see windows/variants/camera.rs).
 */
async setCameraWindowPosition(x: number, y: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_camera_window_position", { x, y }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ignoreCameraWindowPosition(durationMs: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ignore_camera_window_position", { durationMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeCameraWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_camera_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
audioInputLevelChange: AudioInputLevelChange,
currentRecordingChanged: CurrentRecordingChanged,
devicesUpdated: DevicesUpdated,
newNotification: NewNotification,
newScreenshotAdded: NewScreenshotAdded,
onEscapePress: OnEscapePress,
recordingEvent: RecordingEvent,
requestScreenCapturePrewarm: RequestScreenCapturePrewarm,
requestSetTargetMode: RequestSetTargetMode,
targetUnderCursor: TargetUnderCursor
}>({
audioInputLevelChange: "audio-input-level-change",
currentRecordingChanged: "current-recording-changed",
devicesUpdated: "devices-updated",
newNotification: "new-notification",
newScreenshotAdded: "new-screenshot-added",
onEscapePress: "on-escape-press",
recordingEvent: "recording-event",
requestScreenCapturePrewarm: "request-screen-capture-prewarm",
requestSetTargetMode: "request-set-target-mode",
targetUnderCursor: "target-under-cursor"
})

/** user-defined constants **/



/** user-defined types **/

export type Annotation = { id: string; type: AnnotationType; x: number; y: number; width: number; height: number; strokeColor: string; strokeWidth: number; fillColor: string; opacity: number; rotation: number; text: string | null; maskType?: MaskType | null; maskLevel?: number | null; focus?: FocusConfig | null }
export type AnnotationType = "arrow" | "circle" | "rectangle" | "text" | "mask" | "focus"
export type AppTheme = "system" | "light" | "dark"
export type AspectRatio = "wide" | "vertical" | "square" | "classic" | "tall"
export type AudioConfiguration = { mute: boolean; improve: boolean; micVolumeDb: number; micStereoMode: StereoMode; systemVolumeDb: number }
export type AudioInputLevelChange = number
/**
 * A timeline-positioned audio clip (background music or imported audio).
 * 
 * Unlike the recording's mic/system audio (which is keyed to recording clips),
 * these segments live in output/timeline time exactly like zoom/text/mask
 * segments. `path` is resolved relative to the project directory so projects
 * stay portable when moved.
 */
export type AudioTrackSegment = { start: number; end: number; track?: number; path: string; name?: string | null; enabled?: boolean; 
/**
 * Offset into the source audio file (seconds) at which playback begins.
 */
trimStart?: number; volumeDb?: number; fadeIn?: number; fadeOut?: number; 
/**
 * Source duration in seconds, persisted so the UI can clamp resizing
 * without re-decoding the file.
 */
duration?: number | null }
export type BackgroundBlurConfig = { mode: BackgroundBlurMode }
export type BackgroundBlurMode = "off" | "light" | "heavy"
export type BackgroundConfiguration = { source: BackgroundSource; blur: number; padding: number; rounding: number; roundingType: CornerStyle; inset: number; crop: Crop | null; 
/**
 * Normalized (0-1) center of the display rect in output-frame space.
 * `None` keeps the display centered. When a frame is active this is the
 * center of the framed card (chrome included), not the bare video.
 */
displayPosition: XY<number> | null; shadow: number; advancedShadow: ShadowConfiguration | null; border: BorderConfiguration | null; 
/**
 * Decorative frame around the recording. `None` (or `FrameStyle::None`)
 * renders the bare video exactly as before the feature existed.
 */
frame: FrameConfiguration | null; 
/**
 * 3D tilt of the card. `None` renders it perfectly flat, pixel-identical
 * to before this field existed — screenshots are the only surface that
 * ever sets it; video and camera layers never see anything else.
 */
perspective: PerspectiveConfiguration | null; 
/**
 * Film-grain noise laid over the whole background, whatever the source
 * (colour, gradient, wallpaper, imported image). `None`/`0` renders no
 * noise, byte-identical to before this field existed. When unset the
 * renderer falls back to a gradient source's own `noise_intensity`.
 */
noiseIntensity?: number | null; 
/**
 * Grain size for `noise_intensity`. Defaults to `3.0` when noise is on.
 */
noiseScale?: number | null }
export type BackgroundSource = { type: "wallpaper"; path: string | null } | { type: "image"; path: string | null } | { type: "color"; value: [number, number, number]; alpha?: number } | { type: "gradient"; from: [number, number, number]; to: [number, number, number]; angle?: number; noise_intensity?: number | null; noise_scale?: number | null; animated?: boolean | null; animation_speed?: number | null }
export type BorderConfiguration = { enabled: boolean; width: number; color: [number, number, number]; opacity: number }
export type Camera = { hide: boolean; mirror: boolean; position: CameraPosition; 
/**
 * Normalized (0-1) center of the camera rect in output-frame space.
 * Overrides `position` when set.
 */
manualPosition: XY<number> | null; size: number; zoomSize: number | null; rounding: number; shadow: number; advancedShadow: ShadowConfiguration | null; shape: CameraShape; roundingType: CornerStyle; scaleDuringZoom?: number; backgroundBlur?: BackgroundBlurConfig }
export type CameraDeviceSettings = { width: number | null; height: number | null; frameRate: number | null }
export type CameraFormatInfo = { width: number; height: number; frameRate: number }
export type CameraInfo = { device_id: string; model_id: ModelIDType | null; display_name: string }
export type CameraPosition = { x: CameraXPosition; y: CameraYPosition }
export type CameraPreviewShape = "round" | "square" | "full"
export type CameraPreviewState = { size: number; shape: CameraPreviewShape; mirrored: boolean; background_blur?: BackgroundBlurMode }
export type CameraShape = "square" | "source"
export type CameraWithFormats = { deviceId: string; displayName: string; modelId: string | null; formats: CameraFormatInfo[]; bestFormat: CameraFormatInfo | null }
export type CameraXPosition = "left" | "center" | "right"
export type CameraYPosition = "top" | "bottom"
export type CaptionSegment = { id: string; start: number; end: number; text: string; words?: CaptionWord[] }
export type CaptionSettings = { enabled: boolean; font: string; size: number; color: string; backgroundColor: string; backgroundOpacity: number; position: string; italic: boolean; fontWeight: number; outline: boolean; outlineColor: string; exportWithSubtitles: boolean; highlightColor: string; fadeDuration: number; lingerDuration: number; wordTransitionDuration: number; activeWordHighlight: boolean; manualPosition: XY<number> | null; preset: string; animation: string; highlightStyle: string; uppercase: boolean }
export type CaptionTrackSegment = { id: string; start: number; end: number; text: string; words?: CaptionWord[]; fadeDurationOverride?: number | null; lingerDurationOverride?: number | null; positionOverride?: string | null; colorOverride?: string | null; backgroundColorOverride?: string | null; fontSizeOverride?: number | null }
export type CaptionWord = { text: string; start: number; end: number }
export type CaptionsData = { segments: CaptionSegment[]; settings: CaptionSettings; 
/**
 * When true, `segments` are stored in source/recording time and the
 * rendered `timeline.caption_segments` are derived by projecting them
 * through the current edit list, so captions stay aligned to their spoken
 * content as clips are trimmed, deleted, reordered, or inserted. Legacy
 * projects (false) stored segments in already-edited output time and are
 * migrated to source time on first load.
 */
sourceTimed?: boolean }
export type CaptureDisplay = { id: DisplayId; name: string; refresh_rate: number }
export type CaptureDisplayWithThumbnail = { id: string; name: string; refresh_rate: number; thumbnail: string | null }
export type CaptureWindow = { id: WindowId; owner_name: string; name: string; bounds: LogicalBounds; refresh_rate: number; bundle_identifier: string | null }
export type CaptureWindowWithThumbnail = { id: string; owner_name: string; name: string; bounds: LogicalBounds; refresh_rate: number; thumbnail: string | null; app_icon: string | null; bundle_identifier: string | null }
export type ClickSpringConfig = { tension: number; mass: number; friction: number }
export type ClipConfiguration = { index: number; offsets: ClipOffsets; 
/**
 * Whether `offsets` were computed automatically (recording start-time
 * alignment + device sync calibration) rather than entered by the user.
 * Cleared by the editor UI once the user edits an offset.
 */
offsetsAutoCalculated?: boolean }
export type ClipOffsets = { camera?: number; mic?: number; system_audio?: number }
export type ClipSpeedAudioMode = "mute" | "maintainPitch" | "matchSpeed"
export type ClipTransition = { segmentIndex: number; type: ClipTransitionType; duration: number }
export type ClipTransitionType = "cross-fade" | "fade-through-black"
export type CornerStyle = "squircle" | "rounded"
export type Crop = { position: XY<number>; size: XY<number> }
export type CurrentRecordingChanged = null
export type CursorAnimationStyle = "slow" | "smooth" | "mellow" | "fast" | "custom"
export type CursorConfiguration = { hide: boolean; hideWhenIdle: boolean; hideWhenIdleDelay: number; size: number; type: CursorType; animationStyle: CursorAnimationStyle; tension: number; mass: number; friction: number; raw: boolean; motionBlur: number; useSvg: boolean; rotationAmount?: number; baseRotation?: number; clickSpring?: ClickSpringConfig | null; stopMovementInLastSeconds?: number | null }
export type CursorType = "auto" | "pointer" | "circle"
export type DeviceOrModelID = { DeviceID: string } | { ModelID: ModelIDType }
export type DevicesUpdated = { cameras: CameraInfo[]; microphones: string[]; permissions: OSPermissionsCheck }
export type DisplayId = string
export type DisplayInformation = { name: string | null; physical_size: PhysicalSize | null; logical_size: LogicalSize | null; logical_bounds: LogicalBounds | null; refresh_rate: string }
export type EditorPreviewQuality = "quarter" | "half" | "full"
/**
 * Cinematic depth of field over the screenshot: an elliptical plane of focus,
 * with blur growing continuously with distance from it — a circle-of-confusion
 * approximation rather than a sharp-inside/blurred-outside mask. Applies to the
 * screenshot only; the composition's background is never touched.
 * 
 * The region is normalized to the screenshot (0..1 on each axis) so the effect
 * is resolution-independent and survives padding, crop and aspect-ratio changes
 * that move the screenshot within the frame.
 * 
 * `blur`, `depth` and `lens` are the user-facing dials (0-100); the shader
 * derives max circle-of-confusion, falloff curve and bokeh highlight strength
 * from them, so no lens terminology leaks into the UI.
 */
export type FocusConfig = { x: number; y: number; radiusX: number; radiusY: number; 
/**
 * Degrees, clockwise. Lets the plane of focus follow a diagonal subject.
 */
rotation: number; blur: number; depth: number; lens: number; 
/**
 * Asymmetry multipliers: content above the focus reads as further away,
 * below as nearer, so a composition can defocus one side harder. `1.0`
 * each side is symmetric.
 */
nearBlur: number; farBlur: number }
export type FrameConfiguration = { style: FrameStyle; theme: FrameTheme; 
/**
 * Text shown in the browser style's URL pill.
 */
url: string; 
/**
 * Text shown in the macOS window style's title bar.
 */
title: string }
/**
 * Decorative frame drawn around the screen recording (browser window,
 * macOS window, MacBook bezel, ...). The video is inset inside the frame's
 * chrome; the framed card as a whole follows padding / position / zoom
 * exactly like the bare video does today.
 */
export type FrameStyle = 
/**
 * No frame: the video renders bare, exactly as before this feature.
 */
"none" | 
/**
 * A macOS window title bar with traffic-light buttons.
 */
"macOS" | 
/**
 * A Windows 11 window title bar with minimize/maximize/close controls.
 */
"windows" | 
/**
 * A browser toolbar: traffic lights plus a centered URL pill.
 */
"browser" | 
/**
 * A MacBook mockup: black bezel, aluminum body and deck.
 */
"macbook"
export type FrameTheme = "dark" | "light"
export type GeneralSettingsStore = { instanceId?: string; hideDockIcon?: boolean; enableNotifications?: boolean; disableAutoOpenLinks?: boolean; hasCompletedStartup?: boolean; theme?: AppTheme; lastVersion?: string | null; windowTransparency?: boolean; postStudioRecordingBehaviour?: PostStudioRecordingBehaviour; mainWindowRecordingStartBehaviour?: MainWindowRecordingStartBehaviour; custom_cursor_capture2?: boolean; recordingCountdown?: number | null; enableNativeCameraPreview: boolean; autoZoomOnClicks?: boolean; captureKeyboardEvents?: boolean; postDeletionBehaviour?: PostDeletionBehaviour; excludedWindows?: WindowExclusion[]; instantModeMaxResolution?: number; defaultProjectNameTemplate?: string | null; crashRecoveryRecording?: boolean; maxFps?: number; transcriptionHints?: string[]; editorPreviewQuality?: EditorPreviewQuality; studioRecordingQuality?: StudioRecordingQuality; mainWindowPosition?: WindowPosition | null; cameraWindowPosition?: WindowPosition | null; cameraWindowPositionsByMonitorName?: { [key in string]: WindowPosition }; hasCompletedOnboarding?: boolean; outOfProcessMuxer?: boolean; recordingsPath?: string | null; 
/**
 * Custom recordings folders that were used before; recordings left in
 * them stay visible in the library. Most recent last.
 */
previousRecordingsPaths?: string[]; 
/**
 * App version at which camera background blur was disabled after a crash
 * was attributed to the blur pipeline; `None` means blur is allowed.
 * Cleared automatically when the app version changes (one retry per
 * update, since a new ort/wgpu/driver stack may have fixed the crash).
 */
cameraBlurDisabledByCrash?: string | null }
export type GlideDirection = "none" | "left" | "right" | "up" | "down"
export type HapticPattern = "alignment" | "levelChange" | "generic"
export type HapticPerformanceTime = "default" | "now" | "drawCompleted"
export type HotkeysConfiguration = { show: boolean }
export type KeyPressDisplay = { key: string; timeOffset: number }
export type KeyboardData = { settings: KeyboardSettings }
export type KeyboardSettings = { enabled: boolean; font: string; size: number; color: string; backgroundColor: string; backgroundOpacity: number; position: string; fontWeight: number; fadeDuration: number; lingerDuration: number; groupingThresholdMs: number; showModifiers: boolean; showSpecialKeys: boolean; uppercase: boolean }
export type KeyboardTrackSegment = { id: string; start: number; end: number; displayText: string; keys?: KeyPressDisplay[]; fadeDurationOverride?: number | null; positionOverride?: string | null; colorOverride?: string | null; backgroundColorOverride?: string | null; fontSizeOverride?: number | null; uppercaseOverride?: boolean | null }
export type LogicalBounds = { position: LogicalPosition; size: LogicalSize }
export type LogicalPosition = { x: number; y: number }
export type LogicalSize = { width: number; height: number }
export type MainWindowRecordingStartBehaviour = "close" | "minimise"
export type MaskKeyframes = { position?: MaskVectorKeyframe[]; size?: MaskVectorKeyframe[]; intensity?: MaskScalarKeyframe[] }
export type MaskKind = "sensitive" | "highlight"
export type MaskScalarKeyframe = { time: number; value: number }
export type MaskSegment = { start: number; end: number; track?: number; enabled?: boolean; maskType: MaskKind; center: XY<number>; size: XY<number>; feather?: number; opacity?: number; pixelation?: number; darkness?: number; fadeDuration?: number; keyframes?: MaskKeyframes }
export type MaskType = "blur" | "pixelate"
export type MaskVectorKeyframe = { time: number; x: number; y: number }
export type MicrophoneDeviceSettings = { sampleRate: number | null; channels: number | null }
export type MicrophoneFormatInfo = { sampleRate: number; channels: number }
export type MicrophoneInfo = { name: string; sampleRate: number; channels: number; formats: MicrophoneFormatInfo[] }
export type ModelIDType = string
export type NewNotification = { title: string; body: string; is_error: boolean }
/**
 * Emitted once a screenshot is fully written to disk, so an open library
 * view can refresh instead of polling for new files.
 */
export type NewScreenshotAdded = { path: string }
export type OSPermission = "screenRecording" | "camera" | "microphone" | "accessibility"
export type OSPermissionStatus = "notNeeded" | "empty" | "granted" | "denied"
export type OSPermissionsCheck = { screenRecording: OSPermissionStatus; microphone: OSPermissionStatus; camera: OSPermissionStatus; accessibility: OSPermissionStatus }
/**
 * Emitted when Escape is pressed while a target-select overlay is open. The
 * overlays are transparent, click-through-ish windows that may not hold
 * keyboard focus, so Escape is caught as a global shortcut in Rust (see
 * `WindowFocusManager::register_escape`) rather than as a DOM keydown.
 */
export type OnEscapePress = null
/**
 * Screenshot-editor "Perspective" control: tilts the card in 3D. Degrees and
 * a 0-100 depth dial rather than a raw camera distance, so the schema reads
 * the same way the popover's sliders do; `quiro-rendering` converts this into
 * the homography the shader actually wants.
 */
export type PerspectiveConfiguration = { 
/**
 * Leaning away from (positive) or toward (negative) the viewer, degrees.
 */
tiltX: number; 
/**
 * Turning left (negative) or right (positive), degrees.
 */
tiltY: number; 
/**
 * In-plane spin, degrees. No foreshortening on its own.
 */
rotate: number; 
/**
 * 0-100. Higher reads as a wider lens closer to the card, which makes the
 * same tilt angle look more dramatic; lower flattens toward isometric.
 */
depth: number }
export type PhysicalSize = { width: number; height: number }
export type PostDeletionBehaviour = "doNothing" | "reopenRecordingWindow"
export type PostStudioRecordingBehaviour = "openEditor" | "showOverlay"
export type ProjectConfiguration = { aspectRatio: AspectRatio | null; background: BackgroundConfiguration; camera: Camera; audio: AudioConfiguration; cursor: CursorConfiguration; hotkeys: HotkeysConfiguration; timeline: TimelineConfiguration | null; captions: CaptionsData | null; keyboard: KeyboardData | null; clips: ClipConfiguration[]; annotations: Annotation[]; screenMotionBlur?: number; screenMovementSpring?: ScreenMovementSpring; 
/**
 * How text segment font sizes are interpreted. 0 (legacy): the renderer
 * multiplied `font_size` by `size.y / 0.2`, coupling glyph size to the
 * box. 1: `font_size` alone determines glyph size (1080p-relative);
 * legacy configs are migrated on load by baking the box factor into
 * `font_size`. The field-level default keeps old files at 0 while
 * `Default::default()` produces the current version.
 */
textSizeVersion?: number }
export type RecordingEvent = { variant: "Countdown"; value: number } | { variant: "Started" } | { variant: "Stopped" } | { variant: "Paused" } | { variant: "Resumed" } | { variant: "Failed"; error: string } | { variant: "StartFailed"; error: string } | { variant: "InputLost"; input: RecordingInputKind } | { variant: "InputRestored"; input: RecordingInputKind }
/**
 * Which of the optional recording inputs a lifecycle event refers to. The
 * screen itself is never "lost" — only the devices attached alongside it can
 * disappear mid-recording.
 */
export type RecordingInputKind = "microphone" | "camera"
export type RecordingMetaWithMetadata = { prettyName: string; sortTimeMillis: number }
export type RecordingMode = "studio" | "instant" | "screenshot"
export type RecordingSettingsStore = { target: ScreenCaptureTarget | null; micName: string | null; cameraId: DeviceOrModelID | null; mode: RecordingMode | null; systemAudio: boolean; cameraDeviceSettings: { [key in string]: CameraDeviceSettings }; microphoneDeviceSettings: { [key in string]: MicrophoneDeviceSettings } }
export type RecordingTargetMode = "display" | "window" | "area" | "camera"
export type RequestScreenCapturePrewarm = { force?: boolean }
export type RequestSetTargetMode = { target_mode: RecordingTargetMode | null; display_id: string | null }
export type SceneMode = "default" | "cameraOnly" | "hideCamera" | "splitScreen" | 
/**
 * Like [`SceneMode::SplitScreen`], but the screen and camera render as
 * padded, rounded, shadowed cards floating over the background instead
 * of full-bleed halves. Shares [`SplitLayout`] for per-pane pan/zoom.
 */
"floating"
export type SceneSegment = { start: number; end: number; mode?: SceneMode; splitLayout?: SplitLayout | null; transitionIn?: number; transitionOut?: number }
export type ScreenCaptureTarget = { variant: "window"; id: WindowId } | { variant: "display"; id: DisplayId } | { variant: "area"; screen: DisplayId; bounds: LogicalBounds } | { variant: "cameraOnly" }
export type ScreenMovementSpring = { stiffness: number; damping: number; mass: number }
export type ScreenshotMetaWithMetadata = { prettyName: string; sortTimeMillis: number }
export type ScreenshotOcrLine = { text: string; confidence: number | null; bounds: ScreenshotOcrRegion }
export type ScreenshotOcrRegion = { x: number; y: number; width: number; height: number }
export type ScreenshotOcrResult = { text: string; lines: ScreenshotOcrLine[]; engine: string }
export type ScreenshotProjectExport = { imageBytes: number[]; config: ProjectConfiguration; imageWidth: number; imageHeight: number }
export type SerializedScreenshotEditorInstance = { framesSocketUrl: string; path: string; config: ProjectConfiguration | null; prettyName: string; imageWidth: number; imageHeight: number }
export type ShadowConfiguration = { size: number; opacity: number; blur: number }
export type ShowQuiroWindow = { Main: { init_target_mode: RecordingTargetMode | null } } | { Settings: { page: string | null } } | "RecordingsOverlay" | { WindowCaptureOccluder: { screen_id: DisplayId; 
/**
 * Display-relative bounds of the window/area being recorded — the
 * occluder blacks out everything on the display *outside* this
 * rect. `None` blacks out nothing (rather than the whole display),
 * since a target whose bounds couldn't be resolved is the one case
 * where covering the entire screen would be actively misleading.
 */
target_bounds: LogicalBounds | null } } | { TargetSelectOverlay: { display_id: DisplayId; target_mode: RecordingTargetMode | null } } | { CaptureArea: { screen_id: DisplayId } } | { Camera: { centered: boolean } } | { InProgressRecording: { countdown: number | null; capture_target?: ScreenCaptureTarget | null } } | "ModeSelect" | { ScreenshotEditor: { path: string } }
export type SplitLayout = { screenZoom: number; screenPosition: XY<number>; cameraZoom: number; cameraPosition: XY<number> }
export type StereoMode = "stereo" | "monoL" | "monoR"
export type StudioRecordingQuality = "compatibility" | "balanced" | "ultra"
export type TargetUnderCursor = { display_id: DisplayId | null; window: WindowUnderCursor | null }
export type TextSegment = { start: number; end: number; track?: number; enabled?: boolean; content?: string; center?: XY<number>; size?: XY<number>; fontFamily?: string; fontSize?: number; fontWeight?: number; italic?: boolean; color?: string; fadeDuration?: number }
export type TimelineConfiguration = { segments: TimelineSegment[]; transitions: ClipTransition[]; zoomSegments: ZoomSegment[]; sceneSegments?: SceneSegment[]; maskSegments?: MaskSegment[]; textSegments?: TextSegment[]; captionSegments?: CaptionTrackSegment[]; keyboardSegments?: KeyboardTrackSegment[]; audioSegments?: AudioTrackSegment[] }
export type TimelineSegment = { recordingSegment?: number; timescale: number; start: number; end: number; name?: string | null; speedAudioMode?: ClipSpeedAudioMode | null }
export type WindowExclusion = { bundleIdentifier?: string | null; ownerName?: string | null; windowTitle?: string | null }
export type WindowId = string
export type WindowPosition = { x: number; y: number; displayId?: DisplayId | null }
export type WindowUnderCursor = { id: WindowId; app_name: string; bounds: LogicalBounds }
export type XY<T> = { x: T; y: T }
export type ZoomMode = "auto" | { manual: { x: number; y: number } }
export type ZoomSegment = { start: number; end: number; amount: number; mode: ZoomMode; glideDirection?: GlideDirection; glideSpeed?: number; instantAnimation?: boolean; edgeSnapRatio?: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
